apiVersion: v1
kind: Secret
metadata:
  name: wadnr-geoserver-secrets
type: Opaque
data:
  geoserverAdminPassword: {{ .Values.global.secrets.geoserverAdminPassword | b64enc }}
  geoserverAdminUser: {{ .Values.global.secrets.geoserverAdminUser | b64enc }}