CREATE TABLE [dbo].[LoaRawNortheast](
	[LoaRawNortheastID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LoaRawNortheast_LoaRawNortheastID] PRIMARY KEY,
	[Project ID] [varchar](255) NULL,
	[Last Name] [varchar](255) NULL,
	[First Name] [varchar](255) NULL,
	[Application Date] [datetime] NULL,
	[Decision Date] [datetime] NULL,
	[County] [varchar](255) NULL,
	[Forester] [varchar](255) NULL,
	[Forester Phone] [varchar](255) NULL,
	[Forester email] [varchar](255) NULL,
	[Total Acres] [float] NULL,
	[Status] [varchar](255) NULL,
	[Fund Source] [varchar](255) NULL,
	[Letter Date] [datetime] NULL,
	[Project Expiration Date] [datetime] NULL,
	[Stewardship Plan y/n] [varchar](255) NULL,
	[Percent Match] [float] NULL,
	[Treatment 1] [varchar](255) NULL,
	[Cost1] [money] NULL,
	[$/ac 1] [money] NULL,
	[Acres 1] [float] NULL,
	[Treatment 2] [varchar](255) NULL,
	[Cost2] [money] NULL,
	[$/ac 2] [money] NULL,
	[Acres 2] [float] NULL,
	[Treatment 3] [varchar](255) NULL,
	[Cost3] [money] NULL,
	[$/ac 3] [money] NULL,
	[Acres 3] [float] NULL,
	[Treatment 4] [varchar](255) NULL,
	[Cost4] [varchar](255) NULL,
	[$/ac 4] [money] NULL,
	[Acres 4] [float] NULL,
	[Treatment 5] [varchar](255) NULL,
	[Cost5] [varchar](255) NULL,
	[$/ac 5] [money] NULL,
	[Acres 5] [float] NULL,
	[Total Max] [money] NULL,
	[Address] [varchar](255) NULL,
	[City, St, Zip] [varchar](255) NULL,
	[Comment 1 w/date] [varchar](255) NULL,
	[Comment 2 w/date] [varchar](255) NULL,
	[Comment 3 w/date] [varchar](255) NULL,
	[Comment 4 w/date] [varchar](255) NULL,
	[Coordinator] [varchar](255) NULL,
	[Treated Acres] [float] NULL,
	[Contractor?] [varchar](255) NULL,
	[Vendor Name 1] [varchar](255) NULL,
	[Vendor Name 2] [varchar](255) NULL,
	[Vendor Address 1] [varchar](255) NULL,
	[Vendor Address 2] [varchar](255) NULL,
	[Vendor Number] [varchar](255) NULL,
	[Grant #] [varchar](255) NULL,
	[Invoice #] [varchar](255) NULL,
	[Invoice Date] [datetime] NULL,
	[Fund] [varchar](255) NULL,
	[Appn] [varchar](255) NULL,
	[Grant] [varchar](255) NULL,
	[Code] [varchar](255) NULL,
	[Index] [float] NULL,
	[Sub] [varchar](255) NULL,
	[Org] [float] NULL,
	[Match] [money] NULL,
	[Pay] [money] NULL
)
GO
