CREATE TABLE [dbo].[ServiceForestryStage](
    [ServiceForestryStageID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_ServiceForestryStage_ServiceForestryStageID] PRIMARY KEY,
    [RegionTitle] [varchar](50) NULL,
    [ProjectIdentifier] [varchar](600) NOT NULL,
    [ApprovalDate] [date] NULL,
    [County] [varchar](200) NULL,
    [Forester] [varchar](300) NULL,
    [TotalAcres] [decimal](18, 2) NULL,
    [StewardshipPlan] [bit] NULL,
    [PercentMatch] [decimal](9, 4) NULL,
    [FundSource] [varchar](600) NULL,
    [DCStatus] [varchar](200) NULL,
    [DCAllocatedAmount] [money] NULL,
    [DCLetterDate] [date] NULL,
    [DCExpirationDate] [date] NULL,
    [DCTreatment1] [varchar](200) NULL,
    [DCCost1] [money] NULL,
    [DCCostPerAcre1] [money] NULL,
    [DCAcresTreatment1] [decimal](18, 2) NULL,
    [DCTreatment2] [varchar](200) NULL,
    [DCCost2] [money] NULL,
    [DCCostPerAcre2] [money] NULL,
    [DCAcresTreatment2] [decimal](18, 2) NULL,
    [DCTreatment3] [varchar](200) NULL,
    [DCCost3] [money] NULL,
    [DCCostPerAcre3] [money] NULL,
    [DCAcresTreatment3] [decimal](18, 2) NULL,
    [DCTreatment4] [varchar](200) NULL,
    [DCCost4] [money] NULL,
    [DCCostPerAcre4] [money] NULL,
    [DCAcresTreatment4] [decimal](18, 2) NULL,
    [DCTreatment5] [varchar](200) NULL,
    [DCCost5] [money] NULL,
    [DCCostPerAcre5] [money] NULL,
    [DCAcresTreatment5] [decimal](18, 2) NULL,
    [DCTreatment6] [varchar](200) NULL,
    [DCCost6] [money] NULL,
    [DCCostPerAcre6] [money] NULL,
    [DCAcresTreatment6] [decimal](18, 2) NULL,
    [DCTotalMaxAmount] [money] NULL,
    [DCTreatedAcres] [decimal](18, 2) NULL,
    [DCContractor] [bit] NULL,
    [DCVendorName1] [varchar](300) NULL,
    [DCVendorName2] [varchar](300) NULL,
    [DCVendorAddress1] [varchar](300) NULL,
    [DCVendorAddress2] [varchar](300) NULL,
    [DCSwvVendorNumber] [varchar](100) NULL,
    [DCInvoiceDate] [date] NULL,
    [DCProgramIndex] [varchar](50) NULL,
    [DCProjectCode] [varchar](50) NULL,
    [DCMatchAmount] [money] NULL,
    [DCPayAmount] [money] NULL,
    [ItemType] [varchar](100) NULL,
    [SourcePath] [varchar](1000) NULL
)
GO
CREATE NONCLUSTERED INDEX [IDX_ServiceForestryStageProjectIdentifier] ON [dbo].[ServiceForestryStage]([ProjectIdentifier])
GO
