import { Routes } from "@angular/router";
import { adminGuard } from "./shared/guards/admin.guard";
import { authGuard } from "./shared/guards/auth.guard";
import { projectEditGuard } from "./shared/guards/project-edit.guard";
import { UnsavedChangesGuard } from "./shared/guards/unsaved-changes.guard";

export const routeParams = {
    definitionID: "definitionID",
    projectID: "projectID",
    countyID: "countyID",
    dnrUplandRegionID: "dnrUplandRegionID",
    priorityLandscapeID: "priorityLandscapeID",
    projectTypeID: "projectTypeID",
    classificationID: "classificationID",
    tagID: "tagID",
    interactionEventID: "interactionEventID",
    agreementID: "agreementID",
    organizationID: "organizationID",
    programID: "programID",
    fundSourceID: "fundSourceID",
    vendorID: "vendorID",
    personID: "personID",
    taxonomyBranchID: "taxonomyBranchID",
    taxonomyTrunkID: "taxonomyTrunkID",
    roleID: "roleID",
    invoiceID: "invoiceID",
    focusAreaID: "focusAreaID",
    programIndexID: "programIndexID",
    projectCodeID: "projectCodeID",
    classificationSystemID: "classificationSystemID",
    fundSourceAllocationID: "fundSourceAllocationID",
    treatmentID: "treatmentID",
};

export const routes: Routes = [
    // { path: "create-user-callback", loadComponent: () => import("./pages/create-user-callback/create-user-callback.component").then((m) => m.CreateUserCallbackComponent) },
    // { path: "signin-oidc", loadComponent: () => import("./pages/login-callback/login-callback.component").then((m) => m.LoginCallbackComponent) },

    { path: "", loadComponent: () => import("./pages/home/home-index/home-index.component").then((m) => m.HomeIndexComponent) },
    { path: "about", loadComponent: () => import("./pages/about/about.component").then((m) => m.AboutComponent) },
    { path: "additional-resources", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    {
        path: `agreements/:${routeParams.agreementID}`,
        title: "Agreement Detail",
        loadComponent: () => import("./pages/agreements/agreement-detail/agreement-detail.component").then((m) => m.AgreementDetailComponent),
    },
    { path: "agreements", title: "Agreements", loadComponent: () => import("./pages/agreements/agreements.component").then((m) => m.AgreementsComponent) },
    {
        path: "counties",
        title: "Counties",
        loadComponent: () => import("./pages/counties/counties.component").then((m) => m.CountiesComponent),
    },
    {
        path: `counties/:${routeParams.countyID}`,
        title: "County Detail",
        loadComponent: () => import("./pages/counties/county-detail/county-detail.component").then((m) => m.CountyDetailComponent),
    },
    { path: "classification-systems", title: "Classification Systems", loadComponent: () => import("./pages/classification-systems/classification-systems.component").then((m) => m.ClassificationSystemsComponent) },
    {
        path: `classification-systems/:${routeParams.classificationSystemID}`,
        title: "Classification System Detail",
        loadComponent: () => import("./pages/classification-systems/classification-system-detail/classification-system-detail.component").then((m) => m.ClassificationSystemDetailComponent),
    },
    {
        path: "dnr-upland-regions",
        title: "DNR Upland Regions",
        loadComponent: () => import("./pages/dnr-upland-regions/dnr-upland-regions.component").then((m) => m.DNRUplandRegionsComponent),
    },
    {
        path: `dnr-upland-regions/:${routeParams.dnrUplandRegionID}`,
        title: "DNR Upland Region Detail",
        loadComponent: () => import("./pages/dnr-upland-regions/dnr-upland-region-detail.component").then((m) => m.DNRUplandRegionDetailComponent),
    },
    { path: "find-your-forester", title: "Find Your Forester", loadComponent: () => import("./pages/find-your-forester/find-your-forester.component").then((m) => m.FindYourForesterComponent) },
    { path: "focus-areas", title: "DNR LOA Focus Areas", canActivate: [authGuard], loadComponent: () => import("./pages/focus-areas/focus-areas.component").then((m) => m.FocusAreasComponent) },
    {
        path: `focus-areas/:${routeParams.focusAreaID}`,
        title: "Focus Area Detail",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/focus-areas/focus-area-detail/focus-area-detail.component").then((m) => m.FocusAreaDetailComponent),
    },
    { path: "forest-health-monitoring", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "fund-sources", title: "Fund Sources", loadComponent: () => import("./pages/fund-sources/fund-sources.component").then((m) => m.FundSourcesComponent) },
    {
        path: `fund-sources/:${routeParams.fundSourceID}`,
        title: "Fund Source Detail",
        loadComponent: () => import("./pages/fund-sources/fund-source-detail/fund-source-detail.component").then((m) => m.FundSourceDetailComponent),
    },
    {
        path: `fund-source-allocations/:${routeParams.fundSourceAllocationID}`,
        title: "Fund Source Allocation Detail",
        loadComponent: () => import("./pages/fund-source-allocations/fund-source-allocation-detail/fund-source-allocation-detail.component").then((m) => m.FundSourceAllocationDetailComponent),
    },
    {
        path: "interactions-events",
        title: "Interactions/Events",
        loadComponent: () => import("./pages/interactions-events/interactions-events.component").then((m) => m.InteractionsEventsComponent),
    },
    {
        path: `interactions-events/:${routeParams.interactionEventID}`,
        title: "Interaction/Event Detail",
        loadComponent: () => import("./pages/interactions-events/interaction-event-detail/interaction-event-detail.component").then((m) => m.InteractionEventDetailComponent),
    },
    { path: "invoices", title: "Invoices", loadComponent: () => import("./pages/invoices/invoices.component").then((m) => m.InvoicesComponent) },
    {
        path: `invoices/:${routeParams.invoiceID}`,
        title: "Invoice Detail",
        loadComponent: () => import("./pages/invoices/invoice-detail/invoice-detail.component").then((m) => m.InvoiceDetailComponent),
    },
    {
        path: "labels-and-definitions",
        title: "Labels and Definitions",
        loadComponent: () => import("./pages/field-definition-list/field-definition-list.component").then((m) => m.FieldDefinitionListComponent),
    },
    {
        path: `labels-and-definitions/:${routeParams.definitionID}`,
        canActivate: [authGuard],
        loadComponent: () => import("./pages/field-definition-edit/field-definition-edit.component").then((m) => m.FieldDefinitionEditComponent),
    },
    {
        path: "organizations",
        title: "Contributing Organizations",
        loadComponent: () => import("./pages/organizations/organizations.component").then((m) => m.OrganizationsComponent),
    },
    {
        path: `organizations/:${routeParams.organizationID}`,
        title: "Contributing Organization Detail",
        loadComponent: () => import("./pages/organizations/organization-detail/organization-detail.component").then((m) => m.OrganizationDetailComponent),
    },
    { path: "prescribed-fire-seasonal-plans", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    {
        path: "project-steward-organizations",
        title: "Project Steward Organizations",
        loadComponent: () => import("./pages/project-steward-organizations/project-steward-organizations.component").then((m) => m.ProjectStewardOrganizationsComponent),
    },
    {
        path: "priority-landscapes",
        title: "Priority Landscapes",
        loadComponent: () => import("./pages/priority-landscapes/priority-landscapes.component").then((m) => m.PriorityLandscapesComponent),
    },
    {
        path: `priority-landscapes/:${routeParams.priorityLandscapeID}`,
        title: "Priority Landscape Detail",
        loadComponent: () => import("./pages/priority-landscapes/priority-landscape-detail/priority-landscape-detail.component").then((m) => m.PriorityLandscapeDetailComponent),
    },
    { path: "programs", title: "Programs", loadComponent: () => import("./pages/programs/programs.component").then((m) => m.ProgramsComponent) },
    {
        path: `programs/:${routeParams.programID}`,
        title: "Program Detail",
        loadComponent: () => import("./pages/programs/program-detail/program-detail.component").then((m) => m.ProgramDetailComponent),
    },
    { path: "program-indices", title: "Program Indices", loadComponent: () => import("./pages/program-indices/program-indices.component").then((m) => m.ProgramIndicesComponent) },
    {
        path: `program-indices/:${routeParams.programIndexID}`,
        title: "Program Index Detail",
        loadComponent: () => import("./pages/program-indices/program-index-detail/program-index-detail.component").then((m) => m.ProgramIndexDetailComponent),
    },
    { path: "project-codes", title: "Project Codes", loadComponent: () => import("./pages/project-codes/project-codes.component").then((m) => m.ProjectCodesComponent) },
    {
        path: `project-codes/:${routeParams.projectCodeID}`,
        title: "Project Code Detail",
        loadComponent: () => import("./pages/project-codes/project-code-detail/project-code-detail.component").then((m) => m.ProjectCodeDetailComponent),
    },
    { path: "tags", title: "Tags", loadComponent: () => import("./pages/tags/tags.component").then((m) => m.TagsComponent) },
    {
        path: `tags/:${routeParams.tagID}`,
        title: "Tag Detail",
        loadComponent: () => import("./pages/tags/tag-detail/tag-detail.component").then((m) => m.TagDetailComponent),
    },
    {
        path: "taxonomy-branches",
        title: "Taxonomy Branches",
        loadComponent: () => import("./pages/taxonomy-branches/taxonomy-branches.component").then((m) => m.TaxonomyBranchesComponent),
    },
    {
        path: `taxonomy-branches/:${routeParams.taxonomyBranchID}`,
        title: "Taxonomy Branch Detail",
        loadComponent: () => import("./pages/taxonomy-branches/taxonomy-branch-detail/taxonomy-branch-detail.component").then((m) => m.TaxonomyBranchDetailComponent),
    },
    {
        path: "taxonomy-trunks",
        title: "Taxonomy Trunks",
        loadComponent: () => import("./pages/taxonomy-trunks/taxonomy-trunks.component").then((m) => m.TaxonomyTrunksComponent),
    },
    {
        path: `taxonomy-trunks/:${routeParams.taxonomyTrunkID}`,
        title: "Taxonomy Trunk Detail",
        loadComponent: () => import("./pages/taxonomy-trunks/taxonomy-trunk-detail/taxonomy-trunk-detail.component").then((m) => m.TaxonomyTrunkDetailComponent),
    },
    {
        path: `treatments/:${routeParams.treatmentID}`,
        title: "Treatment Detail",
        loadComponent: () => import("./pages/treatments/treatment-detail/treatment-detail.component").then((m) => m.TreatmentDetailComponent),
    },
    {
        path: "roles",
        title: "Roles",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/roles/roles.component").then((m) => m.RolesComponent),
    },
    {
        path: `roles/:${routeParams.roleID}`,
        title: "Role Detail",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/roles/role-detail/role-detail.component").then((m) => m.RoleDetailComponent),
    },
    { path: "vendors", title: "Vendors", canActivate: [authGuard], loadComponent: () => import("./pages/vendors/vendors.component").then((m) => m.VendorsComponent) },
    { path: "people", title: "Users and Contacts", canActivate: [authGuard], loadComponent: () => import("./pages/people/people.component").then((m) => m.PeopleComponent) },
    {
        path: `people/:${routeParams.personID}`,
        title: "User/Contact Detail",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/people/person-detail/person-detail.component").then((m) => m.PersonDetailComponent),
    },
    {
        path: `vendors/:${routeParams.vendorID}`,
        title: "Vendor Detail",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/vendors/vendor-detail/vendor-detail.component").then((m) => m.VendorDetailComponent),
    },
    { path: "projects", title: "Full Project List", loadComponent: () => import("./pages/projects/projects.component").then((m) => m.ProjectsComponent) },
    { path: "projects/map", loadComponent: () => import("./pages/projects/projects-map/projects-map.component").then((m) => m.ProjectsMapComponent) },
    {
        path: `projects/fact-sheet/:${routeParams.projectID}`,
        title: "Project Fact Sheet",
        loadComponent: () => import("./pages/projects/project-fact-sheet/project-fact-sheet.component").then((m) => m.ProjectFactSheetComponent),
    },
    // ProjectCreate: New project - only basics step available until entity exists
    {
        path: "projects/new",
        title: "New Project",
        canActivate: [projectEditGuard],
        loadComponent: () => import("./pages/projects/project-create-workflow/project-create-workflow-outlet.component").then((m) => m.ProjectCreateWorkflowOutletComponent),
        children: [
            { path: "", redirectTo: "basics", pathMatch: "full" },
            { path: "basics", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/basics/basics-step.component").then((m) => m.BasicsStepComponent) },
        ],
    },
    // ProjectCreate: Edit draft/pending project - all steps available
    {
        path: `projects/edit/:${routeParams.projectID}`,
        title: "Edit Project",
        canActivate: [projectEditGuard],
        loadComponent: () => import("./pages/projects/project-create-workflow/project-create-workflow-outlet.component").then((m) => m.ProjectCreateWorkflowOutletComponent),
        children: [
            { path: "", redirectTo: "basics", pathMatch: "full" },
            { path: "basics", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/basics/basics-step.component").then((m) => m.BasicsStepComponent) },
            { path: "location-simple", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/location-simple/location-simple-step.component").then((m) => m.LocationSimpleStepComponent) },
            { path: "location-detailed", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/location-detailed/location-detailed-step.component").then((m) => m.LocationDetailedStepComponent) },
            { path: "priority-landscapes", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/priority-landscapes/priority-landscapes-step.component").then((m) => m.PriorityLandscapesStepComponent) },
            { path: "dnr-upland-regions", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/dnr-upland-regions/dnr-upland-regions-step.component").then((m) => m.DnrUplandRegionsStepComponent) },
            { path: "counties", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/counties/counties-step.component").then((m) => m.CountiesStepComponent) },
            { path: "treatments", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/treatments/treatments-step.component").then((m) => m.TreatmentsStepComponent) },
            { path: "contacts", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/contacts/contacts-step.component").then((m) => m.ContactsStepComponent) },
            { path: "organizations", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/organizations/organizations-step.component").then((m) => m.OrganizationsStepComponent) },
            { path: "expected-funding", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/expected-funding/expected-funding-step.component").then((m) => m.ExpectedFundingStepComponent) },
            { path: "classifications", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/classifications/classifications-step.component").then((m) => m.ClassificationsStepComponent) },
            { path: "photos", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/photos/photos-step.component").then((m) => m.PhotosStepComponent) },
            { path: "documents-notes", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-create-workflow/steps/documents-notes/documents-notes-step.component").then((m) => m.DocumentsNotesStepComponent) },
        ],
    },
    // ProjectUpdate: Update approved project - all steps available
    {
        path: `projects/:${routeParams.projectID}/update`,
        title: "Update Project",
        canActivate: [projectEditGuard],
        loadComponent: () => import("./pages/projects/project-update-workflow/project-update-workflow-outlet.component").then((m) => m.ProjectUpdateWorkflowOutletComponent),
        children: [
            { path: "", redirectTo: "basics", pathMatch: "full" },
            { path: "basics", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/basics/update-basics-step.component").then((m) => m.UpdateBasicsStepComponent) },
            { path: "location-simple", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/location-simple/update-location-simple-step.component").then((m) => m.UpdateLocationSimpleStepComponent) },
            { path: "location-detailed", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/location-detailed/update-location-detailed-step.component").then((m) => m.UpdateLocationDetailedStepComponent) },
            { path: "priority-landscapes", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/priority-landscapes/update-priority-landscapes-step.component").then((m) => m.UpdatePriorityLandscapesStepComponent) },
            { path: "dnr-upland-regions", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/dnr-upland-regions/update-dnr-upland-regions-step.component").then((m) => m.UpdateDnrUplandRegionsStepComponent) },
            { path: "counties", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/counties/update-counties-step.component").then((m) => m.UpdateCountiesStepComponent) },
            { path: "treatments", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/treatments/update-treatments-step.component").then((m) => m.UpdateTreatmentsStepComponent) },
            { path: "contacts", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/contacts/update-contacts-step.component").then((m) => m.UpdateContactsStepComponent) },
            { path: "organizations", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/organizations/update-organizations-step.component").then((m) => m.UpdateOrganizationsStepComponent) },
            { path: "expected-funding", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/expected-funding/update-expected-funding-step.component").then((m) => m.UpdateExpectedFundingStepComponent) },
            { path: "photos", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/photos/update-photos-step.component").then((m) => m.UpdatePhotosStepComponent) },
            { path: "external-links", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/external-links/update-external-links-step.component").then((m) => m.UpdateExternalLinksStepComponent) },
            { path: "documents-notes", canDeactivate: [UnsavedChangesGuard], loadComponent: () => import("./pages/projects/project-update-workflow/steps/documents-notes/update-documents-notes-step.component").then((m) => m.UpdateDocumentsNotesStepComponent) },
        ],
    },
    {
        path: `projects/:${routeParams.projectID}`,
        title: "Project Detail",
        loadComponent: () => import("./pages/projects/project-detail/project-detail.component").then((m) => m.ProjectDetailComponent),
    },
    {
        path: "projects-by-theme",
        title: "Projects By Theme",
        loadComponent: () => import("./pages/classifications/classifications.component").then((m) => m.ClassificationsComponent),
    },
    {
        path: `classifications/:${routeParams.classificationID}`,
        title: "Theme Detail",
        loadComponent: () => import("./pages/classifications/classification-detail/classification-detail.component").then((m) => m.ClassificationDetailComponent),
    },
    { path: "projects-by-type", loadComponent: () => import("./pages/taxonomy/taxonomy.component").then((m) => m.TaxonomyComponent) },
    { path: "project-types", title: "Project Types", loadComponent: () => import("./pages/project-types/project-types.component").then((m) => m.ProjectTypesComponent) },
    {
        path: `project-types/:${routeParams.projectTypeID}`,
        title: "Project Type Detail",
        loadComponent: () => import("./pages/project-types/project-type-detail/project-type-detail.component").then((m) => m.ProjectTypeDetailComponent),
    },
    {
        path: "organization-and-relationship-types",
        title: "Organization Types & Relationship Types",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/admin/organization-and-relationship-types/organization-and-relationship-types.component").then((m) => m.OrganizationAndRelationshipTypesComponent),
    },
    { path: "my-projects", title: "My Projects", canActivate: [authGuard], loadComponent: () => import("./pages/my-projects/my-projects.component").then((m) => m.MyProjectsComponent) },
    { path: "pending-projects", title: "Pending Projects", canActivate: [authGuard], loadComponent: () => import("./pages/pending-projects/pending-projects.component").then((m) => m.PendingProjectsComponent) },
    { path: "featured-projects", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "project-updates", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "homepage-configuration", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "manage-page-content", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "manage-custom-pages", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "internal-setup-notes", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "style-guide", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "upload-excel-files", title: "Upload Excel Files / ETL", canActivate: [adminGuard], loadComponent: () => import("./pages/admin/loa-upload/loa-upload.component").then((m) => m.LoaUploadComponent) },
    { path: "manage-find-your-forester", title: "Manage Find Your Forester", canActivate: [authGuard], loadComponent: () => import("./pages/find-your-forester/manage-find-your-forester/manage-find-your-forester.component").then((m) => m.ManageFindYourForesterComponent) },
    { path: "map-layers", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "jobs", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "json-apis", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "reports/projects", title: "Project Reports", canActivate: [authGuard], loadComponent: () => import("./pages/reports/project-reports/project-reports.component").then((m) => m.ProjectReportsComponent) },
    { path: "reports/ipr", title: "IPR Reports", canActivate: [authGuard], loadComponent: () => import("./pages/reports/ipr-reports/ipr-reports.component").then((m) => m.IprReportsComponent) },
    { path: "reports", title: "Manage Report Templates", canActivate: [authGuard], loadComponent: () => import("./pages/reports/reports.component").then((m) => m.ReportsComponent) },
    {
        path: "gis-bulk-import/:attemptID",
        title: "GIS Bulk Import",
        canActivate: [authGuard],
        loadComponent: () => import("./pages/admin/gis-bulk-import/gis-bulk-import-outlet.component").then((m) => m.GisBulkImportOutletComponent),
        children: [
            { path: "", redirectTo: "instructions", pathMatch: "full" },
            { path: "instructions", loadComponent: () => import("./pages/admin/gis-bulk-import/steps/instructions/instructions-step.component").then((m) => m.InstructionsStepComponent) },
            { path: "upload", loadComponent: () => import("./pages/admin/gis-bulk-import/steps/upload/upload-step.component").then((m) => m.UploadStepComponent) },
            { path: "validate-metadata", loadComponent: () => import("./pages/admin/gis-bulk-import/steps/validate-metadata/validate-metadata-step.component").then((m) => m.ValidateMetadataStepComponent) },
        ],
    },
    { path: "shared-stewardship", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "not-found", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "**", loadComponent: () => import("./shared/components/custom-page/custom-page.component").then((m) => m.CustomPageComponent) },
];
