import { Routes } from "@angular/router";

export const routeParams = {
    definitionID: "definitionID",
    projectID: "projectID",
    countyID: "countyID",
    dnrUplandRegionID: "dnrUplandRegionID",
    priorityLandscapeID: "priorityLandscapeID",
    projectTypeID: "projectTypeID",
    classificationID: "classificationID",
    tagID: "tagID",
    interactionEventID: "interactionEventID",
    agreementID: "agreementID",
    organizationID: "organizationID",
    programID: "programID",
    fundSourceID: "fundSourceID",
    vendorID: "vendorID",
    personID: "personID",
    taxonomyBranchID: "taxonomyBranchID",
    taxonomyTrunkID: "taxonomyTrunkID",
    roleID: "roleID",
    invoiceID: "invoiceID",
    focusAreaID: "focusAreaID",
    programIndexID: "programIndexID",
    projectCodeID: "projectCodeID",
    classificationSystemID: "classificationSystemID",
    fundSourceAllocationID: "fundSourceAllocationID",
    treatmentID: "treatmentID",
};

export const routes: Routes = [
    // { path: "create-user-callback", loadComponent: () => import("./pages/create-user-callback/create-user-callback.component").then((m) => m.CreateUserCallbackComponent) },
    // { path: "signin-oidc", loadComponent: () => import("./pages/login-callback/login-callback.component").then((m) => m.LoginCallbackComponent) },

    { path: "", loadComponent: () => import("./pages/home/home-index/home-index.component").then((m) => m.HomeIndexComponent) },
    { path: "about", loadComponent: () => import("./pages/about/about.component").then((m) => m.AboutComponent) },
    { path: "additional-resources", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    {
        path: `agreements/:${routeParams.agreementID}`,
        title: "Agreement Detail",
        loadComponent: () => import("./pages/agreements/agreement-detail/agreement-detail.component").then((m) => m.AgreementDetailComponent),
    },
    { path: "agreements", title: "Agreements", loadComponent: () => import("./pages/agreements/agreements.component").then((m) => m.AgreementsComponent) },
    {
        path: "counties",
        title: "Counties",
        loadComponent: () => import("./pages/counties/counties.component").then((m) => m.CountiesComponent),
    },
    {
        path: `counties/:${routeParams.countyID}`,
        title: "County Detail",
        loadComponent: () => import("./pages/counties/county-detail/county-detail.component").then((m) => m.CountyDetailComponent),
    },
    { path: "classification-systems", title: "Classification Systems", loadComponent: () => import("./pages/classification-systems/classification-systems.component").then((m) => m.ClassificationSystemsComponent) },
    {
        path: `classification-systems/:${routeParams.classificationSystemID}`,
        title: "Classification System Detail",
        loadComponent: () => import("./pages/classification-systems/classification-system-detail/classification-system-detail.component").then((m) => m.ClassificationSystemDetailComponent),
    },
    {
        path: "dnr-upland-regions",
        title: "DNR Upland Regions",
        loadComponent: () => import("./pages/dnr-upland-regions/dnr-upland-regions.component").then((m) => m.DNRUplandRegionsComponent),
    },
    {
        path: `dnr-upland-regions/:${routeParams.dnrUplandRegionID}`,
        title: "DNR Upland Region Detail",
        loadComponent: () => import("./pages/dnr-upland-regions/dnr-upland-region-detail.component").then((m) => m.DNRUplandRegionDetailComponent),
    },
    { path: "find-your-forester", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "focus-areas", title: "Focus Areas", loadComponent: () => import("./pages/focus-areas/focus-areas.component").then((m) => m.FocusAreasComponent) },
    {
        path: `focus-areas/:${routeParams.focusAreaID}`,
        title: "Focus Area Detail",
        loadComponent: () => import("./pages/focus-areas/focus-area-detail/focus-area-detail.component").then((m) => m.FocusAreaDetailComponent),
    },
    { path: "forest-health-monitoring", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "fund-sources", title: "Fund Sources", loadComponent: () => import("./pages/fund-sources/fund-sources.component").then((m) => m.FundSourcesComponent) },
    {
        path: `fund-sources/:${routeParams.fundSourceID}`,
        title: "Fund Source Detail",
        loadComponent: () => import("./pages/fund-sources/fund-source-detail/fund-source-detail.component").then((m) => m.FundSourceDetailComponent),
    },
    { path: "fund-source-allocations", title: "Fund Source Allocations", loadComponent: () => import("./pages/fund-source-allocations/fund-source-allocations.component").then((m) => m.FundSourceAllocationsComponent) },
    {
        path: `fund-source-allocations/:${routeParams.fundSourceAllocationID}`,
        title: "Fund Source Allocation Detail",
        loadComponent: () => import("./pages/fund-source-allocations/fund-source-allocation-detail/fund-source-allocation-detail.component").then((m) => m.FundSourceAllocationDetailComponent),
    },
    {
        path: "interactions-events",
        title: "Interactions/Events",
        loadComponent: () => import("./pages/interactions-events/interactions-events.component").then((m) => m.InteractionsEventsComponent),
    },
    {
        path: `interactions-events/:${routeParams.interactionEventID}`,
        title: "Interaction/Event Detail",
        loadComponent: () => import("./pages/interactions-events/interaction-event-detail/interaction-event-detail.component").then((m) => m.InteractionEventDetailComponent),
    },
    { path: "invoices", title: "Invoices", loadComponent: () => import("./pages/invoices/invoices.component").then((m) => m.InvoicesComponent) },
    {
        path: `invoices/:${routeParams.invoiceID}`,
        title: "Invoice Detail",
        loadComponent: () => import("./pages/invoices/invoice-detail/invoice-detail.component").then((m) => m.InvoiceDetailComponent),
    },
    {
        path: "labels-and-definitions",
        title: "Labels and Definitions",
        loadComponent: () => import("./pages/field-definition-list/field-definition-list.component").then((m) => m.FieldDefinitionListComponent),
    },
    {
        path: `labels-and-definitions/:${routeParams.definitionID}`,
        loadComponent: () => import("./pages/field-definition-edit/field-definition-edit.component").then((m) => m.FieldDefinitionEditComponent),
    },
    {
        path: "organizations",
        title: "Contributing Organizations",
        loadComponent: () => import("./pages/organizations/organizations.component").then((m) => m.OrganizationsComponent),
    },
    {
        path: `organizations/:${routeParams.organizationID}`,
        title: "Contributing Organization Detail",
        loadComponent: () => import("./pages/organizations/organization-detail/organization-detail.component").then((m) => m.OrganizationDetailComponent),
    },
    { path: "prescribed-fire-seasonal-plans", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    {
        path: "priority-landscapes",
        title: "Priority Landscapes",
        loadComponent: () => import("./pages/priority-landscapes/priority-landscapes.component").then((m) => m.PriorityLandscapesComponent),
    },
    {
        path: `priority-landscapes/:${routeParams.priorityLandscapeID}`,
        title: "Priority Landscape Detail",
        loadComponent: () => import("./pages/priority-landscapes/priority-landscape-detail/priority-landscape-detail.component").then((m) => m.PriorityLandscapeDetailComponent),
    },
    { path: "programs", title: "Programs", loadComponent: () => import("./pages/programs/programs.component").then((m) => m.ProgramsComponent) },
    {
        path: `programs/:${routeParams.programID}`,
        title: "Program Detail",
        loadComponent: () => import("./pages/programs/program-detail/program-detail.component").then((m) => m.ProgramDetailComponent),
    },
    { path: "program-indices", title: "Program Indices", loadComponent: () => import("./pages/program-indices/program-indices.component").then((m) => m.ProgramIndicesComponent) },
    {
        path: `program-indices/:${routeParams.programIndexID}`,
        title: "Program Index Detail",
        loadComponent: () => import("./pages/program-indices/program-index-detail/program-index-detail.component").then((m) => m.ProgramIndexDetailComponent),
    },
    { path: "project-codes", title: "Project Codes", loadComponent: () => import("./pages/project-codes/project-codes.component").then((m) => m.ProjectCodesComponent) },
    {
        path: `project-codes/:${routeParams.projectCodeID}`,
        title: "Project Code Detail",
        loadComponent: () => import("./pages/project-codes/project-code-detail/project-code-detail.component").then((m) => m.ProjectCodeDetailComponent),
    },
    { path: "tags", title: "Tags", loadComponent: () => import("./pages/tags/tags.component").then((m) => m.TagsComponent) },
    {
        path: `tags/:${routeParams.tagID}`,
        title: "Tag Detail",
        loadComponent: () => import("./pages/tags/tag-detail/tag-detail.component").then((m) => m.TagDetailComponent),
    },
    {
        path: "taxonomy-branches",
        title: "Taxonomy Branches",
        loadComponent: () => import("./pages/taxonomy-branches/taxonomy-branches.component").then((m) => m.TaxonomyBranchesComponent),
    },
    {
        path: `taxonomy-branches/:${routeParams.taxonomyBranchID}`,
        title: "Taxonomy Branch Detail",
        loadComponent: () => import("./pages/taxonomy-branches/taxonomy-branch-detail/taxonomy-branch-detail.component").then((m) => m.TaxonomyBranchDetailComponent),
    },
    {
        path: "taxonomy-trunks",
        title: "Taxonomy Trunks",
        loadComponent: () => import("./pages/taxonomy-trunks/taxonomy-trunks.component").then((m) => m.TaxonomyTrunksComponent),
    },
    {
        path: `taxonomy-trunks/:${routeParams.taxonomyTrunkID}`,
        title: "Taxonomy Trunk Detail",
        loadComponent: () => import("./pages/taxonomy-trunks/taxonomy-trunk-detail/taxonomy-trunk-detail.component").then((m) => m.TaxonomyTrunkDetailComponent),
    },
    {
        path: `treatments/:${routeParams.treatmentID}`,
        title: "Treatment Detail",
        loadComponent: () => import("./pages/treatments/treatment-detail/treatment-detail.component").then((m) => m.TreatmentDetailComponent),
    },
    {
        path: "roles",
        title: "Roles",
        loadComponent: () => import("./pages/roles/roles.component").then((m) => m.RolesComponent),
    },
    {
        path: `roles/:${routeParams.roleID}`,
        title: "Role Detail",
        loadComponent: () => import("./pages/roles/role-detail/role-detail.component").then((m) => m.RoleDetailComponent),
    },
    { path: "vendors", title: "Vendors", loadComponent: () => import("./pages/vendors/vendors.component").then((m) => m.VendorsComponent) },
    { path: "people", title: "Users and Contacts", loadComponent: () => import("./pages/people/people.component").then((m) => m.PeopleComponent) },
    {
        path: `people/:${routeParams.personID}`,
        title: "User/Contact Detail",
        loadComponent: () => import("./pages/people/person-detail/person-detail.component").then((m) => m.PersonDetailComponent),
    },
    {
        path: `vendors/:${routeParams.vendorID}`,
        title: "Vendor Detail",
        loadComponent: () => import("./pages/vendors/vendor-detail/vendor-detail.component").then((m) => m.VendorDetailComponent),
    },
    { path: "projects", title: "Full Project List", loadComponent: () => import("./pages/projects/projects.component").then((m) => m.ProjectsComponent) },
    { path: "projects/map", loadComponent: () => import("./pages/projects/projects-map/projects-map.component").then((m) => m.ProjectsMapComponent) },
    {
        path: `projects/fact-sheet/:${routeParams.projectID}`,
        title: "Project Fact Sheet",
        loadComponent: () => import("./pages/projects/project-fact-sheet/project-fact-sheet.component").then((m) => m.ProjectFactSheetComponent),
    },
    {
        path: `projects/:${routeParams.projectID}`,
        title: "Project Detail",
        loadComponent: () => import("./pages/projects/project-detail/project-detail.component").then((m) => m.ProjectDetailComponent),
    },
    {
        path: "projects-by-theme",
        title: "Projects By Theme",
        loadComponent: () => import("./pages/classifications/classifications.component").then((m) => m.ClassificationsComponent),
    },
    {
        path: `classifications/:${routeParams.classificationID}`,
        title: "Theme Detail",
        loadComponent: () => import("./pages/classifications/classification-detail/classification-detail.component").then((m) => m.ClassificationDetailComponent),
    },
    { path: "projects-by-type", loadComponent: () => import("./pages/taxonomy/taxonomy.component").then((m) => m.TaxonomyComponent) },
    {
        path: `project-types/:${routeParams.projectTypeID}`,
        title: "Project Type Detail",
        loadComponent: () => import("./pages/project-types/project-type-detail/project-type-detail.component").then((m) => m.ProjectTypeDetailComponent),
    },
    { path: "shared-stewardship", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "not-found", loadComponent: () => import("./shared/pages").then((m) => m.NotFoundComponent) },
    { path: "**", loadComponent: () => import("./shared/components/custom-page/custom-page.component").then((m) => m.CustomPageComponent) },
];
