/**
 * Comprehensive page registry — the single source of truth for every legacy page
 * and its migration status in the modern Angular app.
 *
 * Every entry represents a navigable page from the legacy MVC app (ProjectFirma.Web).
 * Entries track whether each page has been migrated, restructured into a different UX
 * pattern (workflow, modal), excluded as dead code, or not yet migrated.
 */

export type MigrationStatus = "migrated" | "restructured" | "excluded" | "not-yet-migrated";
export type AuthRequirement = "public" | "auth" | "admin" | "elevated" | "projectEdit" | "pageContent";

export interface PageRegistryEntry {
    /** Unique identifier (kebab-case) */
    id: string;
    /** Human-readable page name */
    name: string;
    /** Feature area grouping */
    area: string;
    /** Legacy MVC route (may contain {token} placeholders) */
    legacyPath: string;
    /** Modern Angular route (null if not migrated or restructured into non-page) */
    modernPath: string | null;
    /** Migration status */
    status: MigrationStatus;
    /** Auth requirement for the modern route */
    auth: AuthRequirement;
    /** Token placeholders to resolve from test-data.ts */
    tokens?: string[];
    /** Whether this page needs extra load time (maps, heavy grids) */
    slowPage?: boolean;
    /** Required when status="excluded" — why this page was not migrated */
    exclusionReason?: string;
    /** Required when status="restructured" — how the UX changed */
    restructureNote?: string;
    /** "page" = standalone route; "modal" = dialog within another page */
    pageType: "page" | "modal";
}

// ─── Registry ──────────────────────────────────────────────────────────────────

export const pageRegistry: PageRegistryEntry[] = [
    // ── Home & About ───────────────────────────────────────────────────────────
    {
        id: "home",
        name: "Home",
        area: "home",
        legacyPath: "/",
        modernPath: "/",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "about",
        name: "About",
        area: "about",
        legacyPath: "/About",
        modernPath: "/about",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },

    // ── Projects ───────────────────────────────────────────────────────────────
    {
        id: "projects-list",
        name: "Projects List",
        area: "projects",
        legacyPath: "/Project/Index",
        modernPath: "/projects",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "project-detail",
        name: "Project Detail",
        area: "projects",
        legacyPath: "/Project/Detail/{projectID}",
        modernPath: "/projects/{projectID}",
        status: "migrated",
        auth: "public",
        tokens: ["projectID"],
        pageType: "page",
    },
    {
        id: "project-fact-sheet",
        name: "Project Fact Sheet",
        area: "projects",
        legacyPath: "/Project/FactSheet/{projectID}",
        modernPath: "/projects/fact-sheet/{projectID}",
        status: "migrated",
        auth: "public",
        tokens: ["projectID"],
        pageType: "page",
    },
    {
        id: "projects-map",
        name: "Projects Map",
        area: "projects",
        legacyPath: "/Results/ProjectMap",
        modernPath: "/projects/map",
        status: "migrated",
        auth: "public",
        slowPage: true,
        pageType: "page",
    },
    {
        id: "my-projects",
        name: "My Projects",
        area: "projects",
        legacyPath: "/ProjectUpdate/AllMyProjects",
        modernPath: "/my-projects",
        status: "migrated",
        auth: "auth",
        pageType: "page",
    },
    {
        id: "pending-projects",
        name: "Pending Projects",
        area: "projects",
        legacyPath: "/Project/Pending",
        modernPath: "/pending-projects",
        status: "migrated",
        auth: "auth",
        pageType: "page",
    },
    {
        id: "featured-projects",
        name: "Featured Projects",
        area: "projects",
        legacyPath: "/Project/FeaturedList",
        modernPath: "/featured-projects",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "project-updates",
        name: "Project Updates",
        area: "projects",
        legacyPath: "/ProjectUpdate/Manage",
        modernPath: "/project-updates",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "projects-by-type",
        name: "Projects By Type",
        area: "projects",
        legacyPath: "/ProjectType/Index",
        modernPath: "/projects-by-type",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "projects-by-theme",
        name: "Projects By Theme",
        area: "classifications",
        legacyPath: "/ProgramInfo/ClassificationSystem/{classificationSystemID}",
        modernPath: "/projects-by-theme",
        status: "migrated",
        auth: "public",
        tokens: ["classificationSystemID"],
        pageType: "page",
    },

    // ── Project Workflows (restructured from single-page forms) ────────────────
    {
        id: "project-create-workflow",
        name: "Project Create",
        area: "projects",
        legacyPath: "/Project/New",
        modernPath: "/projects/new",
        status: "restructured",
        auth: "projectEdit",
        restructureNote: "Legacy single-page form restructured into 13-step wizard workflow (/projects/new/*)",
        pageType: "page",
    },
    {
        id: "project-edit-workflow",
        name: "Project Edit",
        area: "projects",
        legacyPath: "/Project/Edit/{projectID}",
        modernPath: "/projects/edit/{projectID}",
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Legacy single-page form restructured into 13-step wizard workflow (/projects/edit/{id}/*)",
        pageType: "page",
    },
    {
        id: "project-update-workflow",
        name: "Project Update",
        area: "projects",
        legacyPath: "/ProjectUpdate/Instructions/{projectID}",
        modernPath: "/projects/{projectID}/update",
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Legacy multi-page update restructured into 13-step wizard workflow (/projects/{id}/update/*)",
        pageType: "page",
    },

    // ── Project Sub-Page Modals (restructured from standalone pages) ───────────
    {
        id: "project-documents-modal",
        name: "Project Documents",
        area: "projects",
        legacyPath: "/ProjectDocument/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Documents now managed via modal on project detail page and workflow documents-notes step",
        pageType: "modal",
    },
    {
        id: "project-photos-modal",
        name: "Project Photos",
        area: "projects",
        legacyPath: "/ProjectImage/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Photos now managed via workflow photos step and modal on project detail page",
        pageType: "modal",
    },
    {
        id: "project-organizations-modal",
        name: "Project Organizations",
        area: "projects",
        legacyPath: "/ProjectOrganization/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Organizations now managed via workflow organizations step",
        pageType: "modal",
    },
    {
        id: "project-contacts-modal",
        name: "Project Contacts",
        area: "projects",
        legacyPath: "/ProjectContact/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Contacts now managed via workflow contacts step",
        pageType: "modal",
    },
    {
        id: "project-expected-funding-modal",
        name: "Project Expected Funding",
        area: "projects",
        legacyPath: "/ProjectExpectedFunding/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Expected funding now managed via workflow expected-funding step",
        pageType: "modal",
    },
    {
        id: "project-classifications-modal",
        name: "Project Classifications",
        area: "projects",
        legacyPath: "/ProjectClassification/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "Classifications now managed via workflow classifications step",
        pageType: "modal",
    },
    {
        id: "project-external-links-modal",
        name: "Project External Links",
        area: "projects",
        legacyPath: "/ProjectExternalLink/Index/{projectID}",
        modernPath: null,
        status: "restructured",
        auth: "projectEdit",
        tokens: ["projectID"],
        restructureNote: "External links now managed via update workflow external-links step",
        pageType: "modal",
    },

    // ── Agreements ──────────────────────────────────────────────────────────────
    {
        id: "agreements-list",
        name: "Agreements List",
        area: "agreements",
        legacyPath: "/Agreement/Index",
        modernPath: "/agreements",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "agreement-detail",
        name: "Agreement Detail",
        area: "agreements",
        legacyPath: "/Agreement/AgreementDetail/{agreementID}",
        modernPath: "/agreements/{agreementID}",
        status: "migrated",
        auth: "public",
        tokens: ["agreementID"],
        pageType: "page",
    },
    {
        id: "agreement-create-modal",
        name: "Agreement Create",
        area: "agreements",
        legacyPath: "/Agreement/New",
        modernPath: null,
        status: "restructured",
        auth: "elevated",
        restructureNote: "Create/edit now handled via modal dialog on agreements list page",
        pageType: "modal",
    },

    // ── Organizations ──────────────────────────────────────────────────────────
    {
        id: "organizations-list",
        name: "Organizations List",
        area: "organizations",
        legacyPath: "/Organization/Index",
        modernPath: "/organizations",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "organization-detail",
        name: "Organization Detail",
        area: "organizations",
        legacyPath: "/Organization/Detail/{organizationID}",
        modernPath: "/organizations/{organizationID}",
        status: "migrated",
        auth: "public",
        tokens: ["organizationID"],
        pageType: "page",
    },
    {
        id: "project-steward-organizations",
        name: "Project Steward Organizations",
        area: "organizations",
        legacyPath: "/ProjectStewardOrganization/Index",
        modernPath: "/project-steward-organizations",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },

    // ── Fund Sources ───────────────────────────────────────────────────────────
    {
        id: "fund-sources-list",
        name: "Fund Sources List",
        area: "fundSources",
        legacyPath: "/FundSource/Index",
        modernPath: "/fund-sources",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "fund-source-detail",
        name: "Fund Source Detail",
        area: "fundSources",
        legacyPath: "/FundSource/FundSourceDetail/{fundSourceID}",
        modernPath: "/fund-sources/{fundSourceID}",
        status: "migrated",
        auth: "public",
        tokens: ["fundSourceID"],
        pageType: "page",
    },
    {
        id: "fund-source-allocation-detail",
        name: "Fund Source Allocation Detail",
        area: "fundSources",
        legacyPath: "/FundSourceAllocation/FundSourceAllocationDetail/{fundSourceAllocationID}",
        modernPath: "/fund-source-allocations/{fundSourceAllocationID}",
        status: "migrated",
        auth: "public",
        tokens: ["fundSourceAllocationID"],
        pageType: "page",
    },

    // ── Counties ────────────────────────────────────────────────────────────────
    {
        id: "counties-list",
        name: "Counties List",
        area: "counties",
        legacyPath: "/County/Index",
        modernPath: "/counties",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "county-detail",
        name: "County Detail",
        area: "counties",
        legacyPath: "/County/Detail/{countyID}",
        modernPath: "/counties/{countyID}",
        status: "migrated",
        auth: "public",
        tokens: ["countyID"],
        pageType: "page",
    },

    // ── DNR Upland Regions ─────────────────────────────────────────────────────
    {
        id: "dnr-upland-regions-list",
        name: "DNR Upland Regions List",
        area: "dnrUplandRegions",
        legacyPath: "/DNRUplandRegion/Index",
        modernPath: "/dnr-upland-regions",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "dnr-upland-region-detail",
        name: "DNR Upland Region Detail",
        area: "dnrUplandRegions",
        legacyPath: "/DNRUplandRegion/Detail/{dnrUplandRegionID}",
        modernPath: "/dnr-upland-regions/{dnrUplandRegionID}",
        status: "migrated",
        auth: "public",
        tokens: ["dnrUplandRegionID"],
        pageType: "page",
    },

    // ── Priority Landscapes ────────────────────────────────────────────────────
    {
        id: "priority-landscapes-list",
        name: "Priority Landscapes List",
        area: "priorityLandscapes",
        legacyPath: "/PriorityLandscape/Index",
        modernPath: "/priority-landscapes",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "priority-landscape-detail",
        name: "Priority Landscape Detail",
        area: "priorityLandscapes",
        legacyPath: "/PriorityLandscape/Detail/{priorityLandscapeID}",
        modernPath: "/priority-landscapes/{priorityLandscapeID}",
        status: "migrated",
        auth: "public",
        tokens: ["priorityLandscapeID"],
        pageType: "page",
    },

    // ── Focus Areas ────────────────────────────────────────────────────────────
    {
        id: "focus-areas-list",
        name: "Focus Areas List",
        area: "focusAreas",
        legacyPath: "/FocusArea/Index",
        modernPath: "/focus-areas",
        status: "migrated",
        auth: "elevated",
        pageType: "page",
    },
    {
        id: "focus-area-detail",
        name: "Focus Area Detail",
        area: "focusAreas",
        legacyPath: "/FocusArea/Detail/{focusAreaID}",
        modernPath: "/focus-areas/{focusAreaID}",
        status: "migrated",
        auth: "auth",
        tokens: ["focusAreaID"],
        pageType: "page",
    },

    // ── Programs ───────────────────────────────────────────────────────────────
    {
        id: "programs-list",
        name: "Programs List",
        area: "programs",
        legacyPath: "/Program/Index",
        modernPath: "/programs",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "program-detail",
        name: "Program Detail",
        area: "programs",
        legacyPath: "/Program/Detail/{programID}",
        modernPath: "/programs/{programID}",
        status: "migrated",
        auth: "public",
        tokens: ["programID"],
        pageType: "page",
    },

    // ── Tags ───────────────────────────────────────────────────────────────────
    {
        id: "tags-list",
        name: "Tags List",
        area: "tags",
        legacyPath: "/Tag/Index",
        modernPath: "/tags",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "tag-detail",
        name: "Tag Detail",
        area: "tags",
        legacyPath: "/Tag/Detail/{tagName}",
        modernPath: "/tags/{tagID}",
        status: "migrated",
        auth: "public",
        tokens: ["tagID", "tagName"],
        pageType: "page",
    },

    // ── Interactions/Events ────────────────────────────────────────────────────
    {
        id: "interactions-events-list",
        name: "Interactions/Events List",
        area: "interactionsEvents",
        legacyPath: "/InteractionEvent/Index",
        modernPath: "/interactions-events",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "interaction-event-detail",
        name: "Interaction Event Detail",
        area: "interactionsEvents",
        legacyPath: "/InteractionEvent/InteractionEventDetail/{interactionEventID}",
        modernPath: "/interactions-events/{interactionEventID}",
        status: "migrated",
        auth: "public",
        tokens: ["interactionEventID"],
        pageType: "page",
    },
    {
        id: "interaction-event-create-modal",
        name: "Interaction Event Create",
        area: "interactionsEvents",
        legacyPath: "/InteractionEvent/New",
        modernPath: null,
        status: "restructured",
        auth: "auth",
        restructureNote: "Create/edit now handled via modal dialog on interactions/events list and detail pages",
        pageType: "modal",
    },

    // ── Invoices ───────────────────────────────────────────────────────────────
    {
        id: "invoices-list",
        name: "Invoices List",
        area: "invoices",
        legacyPath: "/Invoice/Index",
        modernPath: "/invoices",
        status: "migrated",
        auth: "elevated",
        pageType: "page",
    },
    {
        id: "invoice-detail",
        name: "Invoice Detail",
        area: "invoices",
        legacyPath: "/Invoice/InvoiceDetail/{invoiceID}",
        modernPath: "/invoices/{invoiceID}",
        status: "migrated",
        auth: "public",
        tokens: ["invoiceID"],
        pageType: "page",
    },
    {
        id: "invoice-create-modal",
        name: "Invoice Create",
        area: "invoices",
        legacyPath: "/Invoice/New",
        modernPath: null,
        status: "restructured",
        auth: "elevated",
        restructureNote: "Create/edit now handled via modal dialog on invoices list and detail pages",
        pageType: "modal",
    },

    // ── Taxonomy ───────────────────────────────────────────────────────────────
    {
        id: "taxonomy-branches-list",
        name: "Taxonomy Branches List",
        area: "taxonomy",
        legacyPath: "/TaxonomyBranch/Index",
        modernPath: "/taxonomy-branches",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "taxonomy-branch-detail",
        name: "Taxonomy Branch Detail",
        area: "taxonomy",
        legacyPath: "/TaxonomyBranch/Detail/{taxonomyBranchID}",
        modernPath: "/taxonomy-branches/{taxonomyBranchID}",
        status: "migrated",
        auth: "public",
        tokens: ["taxonomyBranchID"],
        pageType: "page",
    },
    {
        id: "taxonomy-trunks-list",
        name: "Taxonomy Trunks List",
        area: "taxonomy",
        legacyPath: "/TaxonomyTrunk/Index",
        modernPath: "/taxonomy-trunks",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "taxonomy-trunk-detail",
        name: "Taxonomy Trunk Detail",
        area: "taxonomy",
        legacyPath: "/TaxonomyTrunk/Detail/{taxonomyTrunkID}",
        modernPath: "/taxonomy-trunks/{taxonomyTrunkID}",
        status: "migrated",
        auth: "public",
        tokens: ["taxonomyTrunkID"],
        pageType: "page",
    },

    // ── Classifications (Themes) ───────────────────────────────────────────────
    {
        id: "classification-detail",
        name: "Theme Detail",
        area: "classifications",
        legacyPath: "/Classification/Detail/{classificationID}",
        modernPath: "/classifications/{classificationID}",
        status: "migrated",
        auth: "public",
        tokens: ["classificationID"],
        pageType: "page",
    },

    // ── Classification Systems ─────────────────────────────────────────────────
    {
        id: "classification-systems-list",
        name: "Classification Systems List",
        area: "classificationSystems",
        legacyPath: "/ClassificationSystem/Index",
        modernPath: "/classification-systems",
        status: "restructured",
        auth: "public",
        restructureNote: "ClassificationSystemController has no Index action; classification systems were managed inline in legacy, not as a standalone list page",
        pageType: "page",
    },
    {
        id: "classification-system-detail",
        name: "Classification System Detail",
        area: "classificationSystems",
        legacyPath: "/ProgramInfo/ClassificationSystem/{classificationSystemID}",
        modernPath: "/classification-systems/{classificationSystemID}",
        status: "migrated",
        auth: "public",
        tokens: ["classificationSystemID"],
        pageType: "page",
    },

    // ── Project Types ──────────────────────────────────────────────────────────
    {
        id: "project-types-admin",
        name: "Project Types List",
        area: "projectTypes",
        legacyPath: "/ProjectType/Manage",
        modernPath: "/project-types",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "project-type-detail",
        name: "Project Type Detail",
        area: "projectTypes",
        legacyPath: "/ProjectType/Detail/{projectTypeID}",
        modernPath: "/project-types/{projectTypeID}",
        status: "migrated",
        auth: "public",
        tokens: ["projectTypeID"],
        pageType: "page",
    },

    // ── Project Themes (Admin) ─────────────────────────────────────────────────
    {
        id: "project-themes-admin",
        name: "Project Themes",
        area: "projectThemes",
        legacyPath: "/Classification/Index/{classificationSystemID}",
        modernPath: "/project-themes",
        status: "migrated",
        auth: "admin",
        tokens: ["classificationSystemID"],
        pageType: "page",
    },

    // ── Program Indices ────────────────────────────────────────────────────────
    {
        id: "program-indices-list",
        name: "Program Indices List",
        area: "programIndices",
        legacyPath: "/ProgramIndex/Index",
        modernPath: "/program-indices",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "program-index-detail",
        name: "Program Index Detail",
        area: "programIndices",
        legacyPath: "/ProgramIndex/Detail/{programIndexID}",
        modernPath: "/program-indices/{programIndexID}",
        status: "migrated",
        auth: "public",
        tokens: ["programIndexID"],
        pageType: "page",
    },

    // ── Project Codes ──────────────────────────────────────────────────────────
    {
        id: "project-codes-list",
        name: "Project Codes List",
        area: "projectCodes",
        legacyPath: "/ProjectCode/Index",
        modernPath: "/project-codes",
        status: "migrated",
        auth: "public",
        pageType: "page",
    },
    {
        id: "project-code-detail",
        name: "Project Code Detail",
        area: "projectCodes",
        legacyPath: "/ProjectCode/Detail/{projectCodeID}",
        modernPath: "/project-codes/{projectCodeID}",
        status: "migrated",
        auth: "public",
        tokens: ["projectCodeID"],
        pageType: "page",
    },

    // ── Treatments ─────────────────────────────────────────────────────────────
    {
        id: "treatment-detail",
        name: "Treatment Detail",
        area: "treatments",
        legacyPath: "/Treatment/Detail/{treatmentID}",
        modernPath: "/treatments/{treatmentID}",
        status: "migrated",
        auth: "public",
        tokens: ["treatmentID"],
        pageType: "page",
    },

    // ── Admin: People & Roles ──────────────────────────────────────────────────
    {
        id: "roles-list",
        name: "Roles List",
        area: "admin",
        legacyPath: "/Role/Index",
        modernPath: "/roles",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "role-detail",
        name: "Role Detail",
        area: "admin",
        legacyPath: "/Role/Detail/{roleID}",
        modernPath: "/roles/{roleID}",
        status: "migrated",
        auth: "admin",
        tokens: ["roleID"],
        pageType: "page",
    },
    {
        id: "people-list",
        name: "People List",
        area: "admin",
        legacyPath: "/User/Index",
        modernPath: "/people",
        status: "migrated",
        auth: "auth",
        pageType: "page",
    },
    {
        id: "person-detail",
        name: "Person Detail",
        area: "admin",
        legacyPath: "/User/Detail/{personID}",
        modernPath: "/people/{personID}",
        status: "migrated",
        auth: "auth",
        tokens: ["personID"],
        pageType: "page",
    },
    {
        id: "person-edit-modal",
        name: "Person Edit",
        area: "admin",
        legacyPath: "/User/Edit/{personID}",
        modernPath: null,
        status: "restructured",
        auth: "admin",
        tokens: ["personID"],
        restructureNote: "Person editing now handled via modal dialog on person detail page",
        pageType: "modal",
    },
    {
        id: "vendors-list",
        name: "Vendors List",
        area: "admin",
        legacyPath: "/Vendor/Index",
        modernPath: "/vendors",
        status: "migrated",
        auth: "elevated",
        pageType: "page",
    },
    {
        id: "vendor-detail",
        name: "Vendor Detail",
        area: "admin",
        legacyPath: "/Vendor/Detail/{vendorID}",
        modernPath: "/vendors/{vendorID}",
        status: "migrated",
        auth: "elevated",
        tokens: ["vendorID"],
        pageType: "page",
    },

    // ── Admin: Config & Management ─────────────────────────────────────────────
    {
        id: "labels-and-definitions",
        name: "Labels and Definitions",
        area: "admin",
        legacyPath: "/FieldDefinition/Index",
        modernPath: "/labels-and-definitions",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "field-definition-edit",
        name: "Field Definition Edit",
        area: "admin",
        legacyPath: "/FieldDefinition/Edit/{definitionID}",
        modernPath: "/labels-and-definitions/{definitionID}",
        status: "migrated",
        auth: "pageContent",
        tokens: ["definitionID"],
        pageType: "page",
    },
    {
        id: "organization-and-relationship-types",
        name: "Organization and Relationship Types",
        area: "admin",
        legacyPath: "/OrganizationAndRelationshipType/Index",
        modernPath: "/organization-and-relationship-types",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "upload-excel-files",
        name: "Upload Excel Files",
        area: "admin",
        legacyPath: "/ExcelUpload/Index",
        modernPath: "/upload-excel-files",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "map-layers",
        name: "Map Layers",
        area: "admin",
        legacyPath: "/MapLayer/Index",
        modernPath: "/map-layers",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "jobs",
        name: "Jobs",
        area: "admin",
        legacyPath: "/Job/Index",
        modernPath: "/jobs",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "manage-page-content",
        name: "Manage Page Content",
        area: "admin",
        legacyPath: "/FirmaPage/Index",
        modernPath: "/manage-page-content",
        status: "migrated",
        auth: "pageContent",
        pageType: "page",
    },
    {
        id: "manage-custom-pages",
        name: "Manage Custom Pages",
        area: "admin",
        legacyPath: "/CustomPage/Index",
        modernPath: "/manage-custom-pages",
        status: "migrated",
        auth: "pageContent",
        pageType: "page",
    },
    {
        id: "manage-find-your-forester",
        name: "Manage Find Your Forester",
        area: "admin",
        legacyPath: "/FindYourForester/Manage",
        modernPath: "/manage-find-your-forester",
        status: "migrated",
        auth: "elevated",
        pageType: "page",
    },
    {
        id: "internal-setup-notes",
        name: "Internal Setup Notes",
        area: "admin",
        legacyPath: "/Home/InternalSetupNotes",
        modernPath: "/internal-setup-notes",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "homepage-configuration",
        name: "Homepage Configuration",
        area: "admin",
        legacyPath: "/Home/ManageHomePageImages",
        modernPath: "/homepage-configuration",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    // ── Reports ────────────────────────────────────────────────────────────────
    {
        id: "report-templates",
        name: "Report Templates",
        area: "reports",
        legacyPath: "/Reports/Index",
        modernPath: "/reports",
        status: "migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "project-reports",
        name: "Project Reports",
        area: "reports",
        legacyPath: "/Reports/Projects",
        modernPath: "/reports/projects",
        status: "migrated",
        auth: "auth",
        pageType: "page",
    },
    {
        id: "ipr-reports",
        name: "IPR Reports",
        area: "reports",
        legacyPath: "/Reports/IPR",
        modernPath: "/reports/ipr",
        status: "restructured",
        auth: "auth",
        restructureNote: "ReportsController has no IPR action; IPR reporting is new functionality in the modern app",
        pageType: "page",
    },

    // ── Find Your Forester ─────────────────────────────────────────────────────
    {
        id: "find-your-forester",
        name: "Find Your Forester",
        area: "findYourForester",
        legacyPath: "/FindYourForester/Index",
        modernPath: "/find-your-forester",
        status: "migrated",
        auth: "public",
        slowPage: true,
        pageType: "page",
    },

    // ── GIS ────────────────────────────────────────────────────────────────────
    {
        id: "gis-bulk-import",
        name: "GIS Bulk Import",
        area: "admin",
        legacyPath: "/GisProjectBulkUpdate/New",
        modernPath: "/gis-bulk-import/{attemptID}",
        status: "restructured",
        auth: "elevated",
        restructureNote: "Legacy single-page GIS bulk update restructured into multi-step wizard workflow",
        pageType: "page",
    },

    // ── Not Yet Migrated ───────────────────────────────────────────────────────
    {
        id: "style-guide",
        name: "Style Guide",
        area: "admin",
        legacyPath: "/Home/StyleGuide",
        modernPath: "/style-guide",
        status: "not-yet-migrated",
        auth: "admin",
        pageType: "page",
    },
    {
        id: "json-apis",
        name: "JSON APIs",
        area: "admin",
        legacyPath: "/WebServices/Index",
        modernPath: "/json-apis",
        status: "not-yet-migrated",
        auth: "admin",
        pageType: "page",
    },

    // ── Excluded (dead code — not migrated by design) ──────────────────────────
    {
        id: "gis-bulk-update-old",
        name: "GIS Bulk Update (Legacy)",
        area: "excluded",
        legacyPath: "/GisProjectBulkUpdate/Index",
        modernPath: null,
        status: "excluded",
        auth: "admin",
        exclusionReason: "Replaced by new GIS Bulk Import workflow with better UX and validation",
        pageType: "page",
    },
    {
        id: "google-charts",
        name: "Google Charts",
        area: "excluded",
        legacyPath: "/Results/SpendingByOrganizationTypeByOrganization",
        modernPath: null,
        status: "excluded",
        auth: "public",
        exclusionReason: "Google Charts integration removed; replaced by Vega-based charting on relevant pages",
        pageType: "page",
    },
    {
        id: "project-search-results",
        name: "Project Search Results",
        area: "excluded",
        legacyPath: "/Project/Search",
        modernPath: null,
        status: "excluded",
        auth: "public",
        exclusionReason: "Standalone search results page eliminated; grid column filters provide inline search on project list",
        pageType: "page",
    },
    {
        id: "taxonomy-branch-crud",
        name: "Taxonomy Branch CRUD",
        area: "excluded",
        legacyPath: "/TaxonomyBranch/New",
        modernPath: null,
        status: "excluded",
        auth: "admin",
        exclusionReason: "WADNR is leaf-level only (Project Types); Taxonomy Branch/Trunk CRUD is dead code from ProjectFirma fork",
        pageType: "page",
    },
    {
        id: "taxonomy-trunk-crud",
        name: "Taxonomy Trunk CRUD",
        area: "excluded",
        legacyPath: "/TaxonomyTrunk/New",
        modernPath: null,
        status: "excluded",
        auth: "admin",
        exclusionReason: "WADNR is leaf-level only (Project Types); Taxonomy Branch/Trunk CRUD is dead code from ProjectFirma fork",
        pageType: "page",
    },
    {
        id: "project-import-block-list",
        name: "ProjectImportBlockList",
        area: "excluded",
        legacyPath: "/ProjectImportBlockList/Index",
        modernPath: null,
        status: "excluded",
        auth: "admin",
        exclusionReason: "Functionality merged into Program Detail page",
        pageType: "page",
    },
    {
        id: "project-batch-approval",
        name: "Project Batch Approval",
        area: "excluded",
        legacyPath: "/Project/Approve",
        modernPath: null,
        status: "excluded",
        auth: "admin",
        exclusionReason: "Individual project approval on project detail page replaced batch approval workflow",
        pageType: "page",
    },
];
