{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-qa-configmap
data:
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Staging"
  SECRET_PATH: "/app/secrets/wadnrApiSecrets"
  SitkaEmailRedirect: "notifications-qa@sitkatech.com"
  SitkaSupportEmail: "h2o.team@esassoc.com"
  DoNotReplyEmail: "donotreply@laketahoeinfo.org"
  MailLogBcc: ""
  KeystoneOpenIDUrl: "https://identity-qa.sitkatech.com"
  GDALAPIBaseUrl: "http://{{ .Values.global.domains.gdalApi }}"
  SitkaCaptureServiceUrl: "http://{{ .Values.global.domains.sitkacapture }}"
  WebUrl: "https://{{ .Values.global.domains.web }}"
{{ end }}
