CREATE TABLE [dbo].[LoaRawSoutheast](
    [LoaRawSoutheastID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LoaRawSoutheast_LoaRawSoutheastID] PRIMARY KEY,
    [Project ID] [varchar](255) NULL,
    [Last Name] [varchar](255) NULL,
    [First Name] [varchar](255) NULL,
    [Application Date] [varchar](255) NULL,
    [Decision Date] [varchar](255) NULL,
    [County] [varchar](255) NULL,
    [Forester] [varchar](255) NULL,
    [Forester Phone] [varchar](255) NULL,
    [Forester email] [varchar](255) NULL,
    [Total Acres] [varchar](255) NULL,
    [Status] [varchar](255) NULL,
    [Fund Source] [varchar](255) NULL,
    [Allocated Amount] [varchar](255) NULL,
    [Letter Date] [varchar](255) NULL,
    [Project Expiration Date] [varchar](255) NULL,
    [Stewardship Plan y/n] [varchar](255) NULL,
    [Percent Match] [varchar](255) NULL,
    [Treatment 1] [varchar](255) NULL,
    [Cost1] [varchar](255) NULL,
    [$/ac 1] [varchar](255) NULL,
    [Acres 1] [varchar](255) NULL,
    [Treatment 2] [varchar](255) NULL,
    [Cost2] [varchar](255) NULL,
    [$/ac 2] [varchar](255) NULL,
    [Acres 2] [varchar](255) NULL,
    [Treatment 3] [varchar](255) NULL,
    [Cost3] [varchar](255) NULL,
    [$/ac 3] [varchar](255) NULL,
    [Acres 3] [varchar](255) NULL,
    [Treatment 4] [varchar](255) NULL,
    [Cost4] [varchar](255) NULL,
    [$/ac 4] [varchar](255) NULL,
    [Acres 4] [varchar](255) NULL,
    [Treatment 5] [varchar](255) NULL,
    [Cost5] [varchar](255) NULL,
    [$/ac 5] [varchar](255) NULL,
    [Acres 5] [varchar](255) NULL,
    [Treatment 6] [varchar](255) NULL,
    [Cost6] [varchar](255) NULL,
    [$/ac 6] [varchar](255) NULL,
    [Acres 6] [varchar](255) NULL,
    [Total Max] [varchar](255) NULL,
    [Total_per_acre] [varchar](255) NULL,
    [Address] [varchar](255) NULL,
    [City, St, Zip] [varchar](255) NULL,
    [Comment 1 w/date] [varchar](255) NULL,
    [Comment 2 w/date] [varchar](255) NULL,
    [Comment 3 w/date] [varchar](255) NULL,
    [Comment 4 w/date] [varchar](255) NULL,
    [Coordinator] [varchar](255) NULL,
    [Treated Acres] [varchar](255) NULL,
    [Contractor?] [varchar](255) NULL,
    [Vendor Name 1] [varchar](255) NULL,
    [Vendor Name 2] [varchar](255) NULL,
    [Vendor Address 1] [varchar](255) NULL,
    [Vendor Address 2] [varchar](255) NULL,
    [Vendor Number] [varchar](255) NULL,
    [Grant #] [varchar](255) NULL,
    [Invoice #] [varchar](255) NULL,
    [Invoice Date] [varchar](255) NULL,
    [Fund] [varchar](255) NULL,
    [Appn] [varchar](255) NULL,
    [Grant] [varchar](255) NULL,
    [Index] [varchar](255) NULL,
    [Code] [varchar](255) NULL,
    [Sub] [varchar](255) NULL,
    [Org] [varchar](255) NULL,
    [Match] [varchar](255) NULL,
    [Pay] [varchar](255) NULL,
    [Total Spent] [varchar](255) NULL,
    [Actual Spent] [varchar](255) NULL,
    [Coordinator Email] [varchar](255) NULL,
    [Coordinator #] [varchar](255) NULL,
    [BR] [varchar](255) NULL,
    [TH] [varchar](255) NULL,
    [PR] [varchar](255) NULL,
    [SL] [varchar](255) NULL,
    [PL] [varchar](255) NULL,
    [RX] [varchar](255) NULL,
    [Reconciled in Grant tracker] [varchar](255) NULL,
    [Comments in grant tracker] [varchar](255) NULL,
    [1/20/2021 10:06] [varchar](255) NULL,
    [True Allocation] [varchar](255) NULL,
    [Agreement Contract Number] [varchar](255) NULL
)
GO
