CREATE TABLE [dbo].[ProjectUpdateBatch](
	[ProjectUpdateBatchID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_ProjectUpdateBatch_ProjectUpdateBatchID] PRIMARY KEY,
	[ProjectID] [int] NOT NULL CONSTRAINT [FK_ProjectUpdateBatch_Project_ProjectID] FOREIGN KEY REFERENCES [dbo].[Project]([ProjectID]),
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdatePersonID] [int] NOT NULL CONSTRAINT [FK_ProjectUpdateBatch_Person_LastUpdatePersonID_PersonID] FOREIGN KEY REFERENCES [dbo].[Person]([PersonID]),
	[BasicsComment] [varchar](1000) NULL,
	[ExpendituresComment] [varchar](1000) NULL,
	[LocationSimpleComment] [varchar](1000) NULL,
	[LocationDetailedComment] [varchar](1000) NULL,
	[BudgetsComment] [varchar](1000) NULL,
	[ProjectUpdateStateID] [int] NOT NULL CONSTRAINT [FK_ProjectUpdateBatch_ProjectUpdateState_ProjectUpdateStateID] FOREIGN KEY REFERENCES [dbo].[ProjectUpdateState]([ProjectUpdateStateID]),
	[IsPhotosUpdated] [bit] NOT NULL,
	[BasicsDiffLog] [dbo].[html] NULL,
	[ExpendituresDiffLog] [dbo].[html] NULL,
	[BudgetsDiffLog] [dbo].[html] NULL,
	[ExternalLinksDiffLog] [dbo].[html] NULL,
	[NotesDiffLog] [dbo].[html] NULL,
	[GeospatialAreaComment] [varchar](1000) NULL,
	[ExpectedFundingComment] [varchar](1000) NULL,
	[ExpectedFundingDiffLog] [varchar](max) NULL,
	[OrganizationsComment] [varchar](1000) NULL,
	[OrganizationsDiffLog] [varchar](1) NULL,
	[NoExpendituresToReportExplanation] [varchar](max) NULL,
	[ContactsComment] [varchar](1000) NULL,
	[NoRegionsExplanation] [varchar](4000) NULL,
	[ProjectAttributesComment] [varchar](1000) NULL,
	[ProjectAttributesDiffLog] [dbo].[html] NULL,
	[NoPriorityLandscapesExplanation] [varchar](4000) NULL,
	[NoCountiesExplanation] [varchar](4000) NULL
)
GO