apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gdalapi.fullname" . }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      {{- include "gdalapi.selectorLabels" . | nindent 6 }}
