{{ if eq .Values.global.env.name "prod" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalar.fullname" . }}-prod-configmap
data:
  SECRET_PATH: "/app/secrets/wadnrScalarSecrets"
  ASPNETCORE_ENVIRONMENT: "Production"
{{ end }}
