global:
  env:
    name: "qa"
    dbServer: "db-server.database.windows.net"
    databaseName: "WADNRDB"
    sqlUsername: "SqlAdministrator"
    sqlGeoserverUsername: "WADNRGeo"
  domains:
    api: "internalapi-wadnr.esa-qa.sitkatech.com"
    web: "wadnr.esa-qa.sitkatech.com"
    geoserver: "geoserver-wadnr.esa-qa.sitkatech.com"
    scalarApi: "api-wadnr.esa-qa.sitkatech.com"
    sitkacapture: "wadnr-sitkacapture"
  secrets:
    geoserverSqlServerPassword: "passwordhere"
    geoserverAdminUser: "geomaster"
    geoserverAdminPassword: "geomasterPassword"
    applicationStorageAccountName: "wadnrappqa"
    applicationStorageAccountKey:  "longkeyreplacedhere"
    apiSqlPassword: "passwordhere"
    sendGridApiKey: "sendgridapikeyhere"
    hangfirePassword: "passwordhere"
    keystoneOpenIDClientSecret: "secrethere"
    recaptchaV3SiteKey: "recaptchaV3SiteKeyHere"
    recaptchaV3SecretKey: "recaptchaV3SecretKeyHere"
    dataImportAuthUsername: "usernamehere"
    dataImportAuthPassword: "passwordhere"
    arcGisClientId: "clientidhere"
    arcGisClientSecret: "clientsecrethere"

api:
  replicaCount: 1
  image:
    repository: containersesaqa.azurecr.io/wadnr/api
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "1G"
    limits:
      memory: "8G"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "azure-application-gateway"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/request-timeout: "300"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}

web:
  replicaCount: 1
  image:
    repository: containersesaqa.azurecr.io/wadnr/web
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "1G"
    limits:
      memory: "2G"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "azure-application-gateway"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/request-timeout: "1200"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}

geoserver:
  replicaCount: 1
  image:
    repository: kartoza/geoserver
    pullPolicy: Always
    tag: "2.28.0"
    # Overrides the image tag whose default is the chart appVersion.
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "4G"
    limits:
      memory: "8G"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "azure-application-gateway"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}

gdalapi:
  replicaCount: 1
  image:
    repository: containersesaqa.azurecr.io/wadnr/gdalapi
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "4G"
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector:
    agentpool: appnodepool
  tolerations: []
  affinity: {}

sitkacapture:
  replicaCount: 1
  image:
    repository: containersesaqa.azurecr.io/sitkacapture:latest
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1G"
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector:
    agentpool: appnodepool
  tolerations: []
  affinity: {}

scalar:
  replicaCount: 1
  image:
    repository: containersesaqa.azurecr.io/wadnr/scalar
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "2G"
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "azure-application-gateway"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/request-timeout: "300"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector:
    agentpool: appnodepool
  tolerations: []
  affinity: {}
